spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: MyBalls.88
  jpa:
    hibernate.ddl-auto: create-drop #(solo habilita este cuando crees por primera vez la base)
    show-sql: true
